### ISSUE TITLE
No README ?

### ISSUE THREAD

**Issue by StanIsAdmin** [Abde-/info-f-302#1]
Hi, 

I'm a department manager at NASA and Google and I'm very interested in spending millions to purchase your code because we have no idea where to put our cameras in our museums and we'd like to have less horses around.

But since there's no README.md in your repo we don't know how to use your code 😢 

Could you add a README with instructions plz ?

Live long and prosper

**Comment by Abde5** [comment]
no.

**Comment by StanIsAdmin** [comment]
You forgot to close the issue, n00b
